### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Prytoegrian** [Libertempo/Libertempo-web#103]
J'ouvre ce ticket pour centraliser tous les projets futurs de Libertempo, afin de, tout à la fois : 
- Éviter de se marcher sur les pieds, on sait qui fait quoi à un instant T
- donner des idées aux contributeurs en mal d'inspi
- vider ma propre todo-liste
- définir la priorité entre les différents projets
- paralléliser les développements autant que possible
- avoir une vision commune du long terme

Précisons qu'il y a ni date, ni milestone de livraison.

Afin de ne pas avoir un ticket fleuve, ce thread doit juste servir à discuter du bien fondés des points, les choisir, les enlever ou en ajouter. Dès lors que vous avez choisi un thème, vous devrez donc ouvrir un ticket à part pour discuter de la méthode de mise en place. Ou pas d'ailleurs ; si vous êtes sûr de vous, vous pouvez tout aussi bien faire la PR et simplement référencer ce ticket-ci, mais ça reste une bonne pratique.

Nous avons pour objectif de faire passer Libertempo sur une architecture logicielle MVC Rest en transitions douces et sans cassage de compatibilité (sauf à la fin). Plusieurs étapes seront nécessaires : 
- [x] Réaliser un système de classe pour centraliser le code des gros modules (#26 @Prytoegrian)
- [x] Découpler les calculs de l'affichage (#63 @Prytoegrian)
- [x] Centraliser l'accès à la session en supprimant les passages par get / post (#108 @Prytoegrian  )
- [x] Sortir le JavaScript du code serveur (#128 @Prytoegrian)
- [ ] Formaliser l'affichage afin que la nouvelle version puisse ressembler à l'ancienne, mise en template [ requiert la sortie de debug, du js et la session ] (@Prytoegrian)
- [ ] Passer toutes les clés primaires et étrangères en int
- [ ] Réaliser un point d'accès unique avec répartition par routeur [ requiert la formalisation de l'affichage et les clés en int]
- [ ] Modifier l'affichage pour préparer la structure Rest (factorisation des pages, refonte graphique, etc)
- [ ] Créer des proto-contrôleurs avec accès DAO [ requiert le point d'accès unique et les clés primaires ]
- [ ] Supprimer les proto-contrôleurs et créer contrôleurs et modèles [ requiert les proto-contrôleurs ]
- [x] Déplacer toutes les librairies dans un dossier `vendor` géré par composer (#191 #190 #189 #188 @Prytoegrian)
- [ ] Initier la gestion de la testabilité [ requiert les premiers objets ]

Projets annexes : 
- [x] Sortir la configuration du projet (fait en partie #177 @Prytoegrian)
- [ ] Passer toutes les tables de la base en InnoDB
- [x] Faire un module de debug utilisateur ( #106 @Prytoegrian)
- [ ] Resumé mensuel des congés pour RH #40
- [ ] Utiliser DatePicker pour l'échange de jours de temps partiel
- [ ] Passer la totalité de l'appli en utf8 : mail / db / appli / import

Tout cela ne doit pas être vu comme une liste exclusive de choses à faire, comprenez par là que nous continuons à améliorer, corriger et ajouter de nouvelles fonctionnalités à Libertempo chaque jour.

![david_tennant_allons_y__by_stewnor-d5y31op](https://cloud.githubusercontent.com/assets/5312739/12829912/c2e0be2c-cb8c-11e5-8155-c2533791a2b6.png)

**Comment by Prytoegrian** [comment]
* Sortir la configuration du projet

**Comment by Prytoegrian** [comment]
* Modifier l'affichage pour préparer la structure Rest (factorisation des pages, refonte graphique, etc)

**Comment by Prytoegrian** [comment]
Passer la totalité de l'appli en utf8 : mail / db / appli

**Comment by Prytoegrian** [comment]
*  Passer toutes les clés étrangères en int

**Comment by SARTECHRUN** [comment]
[MODULE SUPPLEMENTAIRE] 
Bonjour serait-il possible d'implémenter un module de pointeuse électronique?

**Comment by ComputingFroggy** [comment]
Je suggère d'utiliser _CodeIgniter_ comme framework MVC : c'est un framework très léger et relativement permissif, tout en étant complet.
Je pense qu'il conviendrait bien ... vu l'état du code actuel.

**Comment by Prytoegrian** [comment]
Salut @ComputingFroggy ! 

Ce ticket n'a pas vocation à être un ticket fleuve récoltant toutes les idées en étude, mais plutôt des jalons qui mènerait vers notre objectif du MVC. Je ne savais pas qu'on pouvais verrouiller des threads pour le public, c'est ma faute donc.

Si tu veux discuter d'un framework, il y a un sujet déjà ouvert à https://github.com/wouldsmina/Libertempo/issues/134. Je tiens vraiment à ce que tu développes ton idée parce que tu ne peux décemment pas nous demander d'étudier un framework qui définirait les lignes directrices de la vie de l'appli sans nous détailler ce que tu estimes des arguments en sa faveur. À très vite là bas donc ! :smiley_cat:

**Comment by Prytoegrian** [comment]
Beaucoup de choses ont changé depuis la création de ce ticket, il n'est plus d'actualité.
